### ISSUE TITLE
Heatmap not displaying correctly

### ISSUE THREAD

**Issue by martacds** [tripal/tripal_analysis_expression#301]
Hi!
I placed the heatmap without any problems but it displays like this:
![Capture33](https://user-images.githubusercontent.com/47527249/59272711-88162080-8c4e-11e9-95a4-2d60e7ca1383.PNG)

I have the same heatmap displaying correctly on another place. 
![Capture34](https://user-images.githubusercontent.com/47527249/59272834-c0b5fa00-8c4e-11e9-9106-1d962307f34b.PNG)

How do I fix this?
Thank you!

**Comment by martacds** [comment]
Hi, 
Figured out what was wrong! A few of the BioSample names were too long so it deformed the heatmap even when they weren't on display.

May I suggest a warning about this or an update so that one single BioSample name doesn't deform the heatmap for all analyses?

Thanks anyway!

**Comment by almasaeed2010** [comment]
Hello @martacds 

Thanks for reporting the issue (and the fix!). I'll try to add in some code to trim the names when I get a chance. 

Thanks!

**Comment by almasaeed2010** [comment]
Issue has been fixed on master. Please feel free to re-open the issue if the fix doesn't help.

Thanks!

**Comment by martacds** [comment]
So it fixed the space the name occupies by putting it horizontally and clipping the excess but the heatmap still gets smaller. 
![Screenshot from 2019-06-12 14-09-19](https://user-images.githubusercontent.com/47527249/59353864-d0e7db00-8d1b-11e9-8918-00c6f702c7aa.png)

In the example, I added a bunch of XXs at the end of the first BioSample (which has the longest name) and the heatmap got progressively smaller despite the fix.

**Comment by almasaeed2010** [comment]
This seems like an issue with JS library that generates the heatmap. Could you try resizing your browser window? Resizing the window should prompt it to redraw the map and recalculate the space needed. If the map is fixed after resizing, then we can make sure it reset the height prior to drawing the first time.

**Comment by martacds** [comment]
I tried maximizing and minimizing the window (I assume that's what you meant) and it's still not right.

The previous screenshot I sent had a small window and after maximizing it showed up like this:
![Screenshot from 2019-06-12 14-19-08](https://user-images.githubusercontent.com/47527249/59354546-3ee0d200-8d1d-11e9-99a4-3219730bdd45.png)

**Comment by almasaeed2010** [comment]
Sorry I meant resizing the browser window by making the width of the window smaller or larger (dragging the edge of the window using the mouse).

**Comment by martacds** [comment]
Yes, I did that. It looks the same as before.

**Comment by martacds** [comment]
All I did was use a previous dataset and edit the BioSample name. I added a bunch of XXXs to the BioSample name to make it really long (it currently has the following name: "Embryos ; S1 to S8 [from fruit] xxxxxxxxxxxxxxxxxxxxxxxxxx").
